branch-defaults:
  main:
    environment: passGen-dev
global:
  application_name: passGen
  branch: null
  default_ec2_keyname: EC2 Instance 1
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
